name: Build and release FXGL dialogue editor

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        delete_release: true # default: false
        tag_name: tag-auto
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: tag-auto
        release_name: release-auto
        body: This is the latest development build of FXGL Dialogue Editor. Latest stable build can be found in [FXGL releases](https://github.com/AlmasB/FXGL/releases).
        draft: false
        prerelease: false

